---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgCaN7KH3v7Q7t+MRTHmwckuCWhdxn68cb1urcQjfNX95VjsWpAL7s+mz2yJDriJF4jZmF5h252kFBWN4hR/lk6K5lJAGyN7aVc57Kg2qOKs7PH2eDvhC3jmJGy2SLR0
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque
