apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgC4C+QKHkRbDyfYn4sF7nLwkdNP9m6D/naWde8inIk6CtyrLUYiOIRFbkz9n6q5Z4XXoQxX84JRr7lIeYSc4nQXgWE3l0z1M/yM6p9wnYFgAzlTPkxDdlZtcYvUGAsE
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
                                                                                                                                             