---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgBJS84zxXi/z49sch0cnU1OOja5vRYGLNTUdSoaTmWg/3y09PMpEytVDWQAxBfrLy5/T4GO/HD+kutSdaDSVCHFIvsuBvBs/KEMS1QxX436L5r31hSXUjwlSBl+FeIf
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default