---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgA3ou8JpGwnL6nrE2k3UPgJT/da+ZXYZ6VECigBi24bSI/M/mbA4d0mCynmT44rGWwsGWWoiTZ2BkPM3UZqyPRW0lfjjtmOx3fBEKMPfWWHcWrP6KQ4k4JjJrOwwOW/
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default