---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgCxcTVg15oVssQjAswYM+gsJ2HH49FEIR93sDBpguplArYijEJroLLjVR9e4IsCZeNLzOLl3btOVz4TvajmibnxnO5/lnE9ZtiktWOeAgaZ2i+B3clf8LGD8HiyVfU3
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default